# Authorino Metrics Configuration Patch
# This patch enables deep metrics for Authorino to expose request-level data
# Apply after Kuadrant installation: kubectl apply -f 08-authorino-metrics-patch.yaml
---
apiVersion: operator.authorino.kuadrant.io/v1beta1
kind: Authorino
metadata:
  name: authorino
  namespace: kuadrant-system
spec:
  # Enable deep metrics for request-level observability
  metrics:
    deep: true
    port: 8080
  # Keep existing configuration from Kuadrant operator
  clusterWide: true
  healthz: {}
  listener:
    ports: {}
    tls:
      enabled: false
  oidcServer:
    tls:
      enabled: false
  supersedingHostSubsets: true
  tracing:
    endpoint: ""
  volumes: {}