# Gateway-level Token Rate Limiting Policy - Testing Configuration
# This policy applies token-based rate limiting with very low limits for easy testing
# Automatically tracks tokens from response bodies (usage.total_tokens)
# Uses the same user groups as the request-based rate limiting policy
---
apiVersion: kuadrant.io/v1alpha1
kind: TokenRateLimitPolicy
metadata:
  name: gateway-token-rate-limits
  namespace: llm
spec:
  targetRef:
    group: gateway.networking.k8s.io
    kind: Gateway
    name: inference-gateway
  limits:
    free-user-tokens:
      rates:
        - limit: 3          # 3 tokens per 2 minutes for free users
          window: 2m
      when:
        - predicate: |
            auth.identity.groups.split(",").exists(g, g == "free")
      counters:
        - expression: auth.identity.userid
    
    premium-user-tokens:
      rates:
        - limit: 6          # 6 tokens per 2 minutes for premium users
          window: 2m
      when:
        - predicate: |
            auth.identity.groups.split(",").exists(g, g == "premium")
      counters:
        - expression: auth.identity.userid
    
    enterprise-user-tokens:
      rates:
        - limit: 12         # 12 tokens per 2 minutes for enterprise users
          window: 2m
      when:
        - predicate: |
            auth.identity.groups.split(",").exists(g, g == "enterprise")
      counters:
        - expression: auth.identity.userid